bulle_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

from .views import IndexPage
from .views import InfoPage
from .views import ContactoPage
from .views import ShopPage
from .views import MayoristaPage

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", IndexPage.as_view(),name="index"),
    path("info/", InfoPage.as_view(),name="info"),
    path("shop/", ShopPage.as_view(),name="shop"),
    path("contacto/", ContactoPage.as_view(),name="contacto"),
    path("mayorista/", MayoristaPage.as_view(),name="mayorista"),
    path("tienda/", include("tienda_app.urls"))
]

tienda_app/urls.py
from django.contrib import admin
from django.urls import path , include

from .router import router

from .views import      TiendaListView   \
                    ,   TiendaDetailView \
                    ,   TiendaCreateView \
                    ,   TiendaUpdateView \
                    ,   TiendaDeleteView

app_name = "tienda"

urlpatterns = [
    path("", TiendaListView.as_view(), name="all"),
    path("create/", TiendaCreateView.as_view(), name="create"),
    path("<int:pk>/detail/", TiendaDetailView.as_view(), name="detail"),
    path("<int:pk>/update/", TiendaUpdateView.as_view(), name="update"),
    path("<int:pk>/delete/", TiendaDeleteView.as_view(), name="delete")
]

urlpatterns += router.urls

tienda_app/models.py
from django.db import models
from django.db.models import Model
# Create your models here.
class Tienda(models.Model):
    """
    Atributos de clase que son usadas por herencia de la clase Model

    """
    nombre = models.CharField(max_length=100, default="tienda x")
    rubro = models.CharField(max_length=100, default="rubro x", blank=False, null=False)
    contacto = models.EmailField(max_length=100, default="no_contact@mail")
    ubicacion = models.CharField(max_length=100, default="Tienda online")
    fecha_habilitacion = models.DateField(blank=False, null=False, auto_now=True)


    # podemos crear la tabla con un nombre especifico pero se lo tenemos
    # que indicar directamente en la metaclase

    class Meta:
        db_table = "tiendas_buenos_aires_arg"
        


    def __str__(self):
        return f"El nombre de la tienda es: {self.nombre}, rubro{self.rubro}"

    def get_fields(self):
        return [
            (field.verbose_name, field.value_from_object(self))
            for field in self.__class__._meta.fields[1:]
        ]

bulle_project/views.py
from django.views.generic import TemplateView

class IndexPage(TemplateView):
    template_name = 'index.html'

class ShopPage(TemplateView):
    template_name = 'product.html'

class ContactoPage(TemplateView):
    template_name = 'contact.html'

class InfoPage(TemplateView):
    template_name = 'about.html'

class MayoristaPage(TemplateView):
    template_name = 'mayorista.html'

    

tienda_app/views.py
from django.urls import reverse_lazy
from django.views import View

from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import DeleteView, UpdateView, CreateView


from .models import Tienda

# Create your views here.


class TiendaBaseView(View):
    template_name = 'tienda.html'
    model = Tienda
    fields = '__all__'
    success_url = reverse_lazy('tienda:all')


class TiendaListView(TiendaBaseView,ListView):
    """
    ESTO ME PERMITE CREAR UNA VISTA CON LOS Tienda
    """

class TiendaDetailView(TiendaBaseView,DetailView):
    template_name = "tienda_detail.html"

class TiendaCreateView(TiendaBaseView,CreateView):
    template_name = "tienda_create.html"
    extra_context = {
        "tipo": "Crear tienda"
    }


class TiendaUpdateView(TiendaBaseView,UpdateView):
    template_name = "tienda_create.html"
    extra_context = {
        "tipo": "Actualizar tienda"
    }

class TiendaDeleteView(TiendaBaseView,DeleteView):
    template_name = "tienda_delete.html"
    extra_context = {
        "tipo": "Borrar tienda"
    }
# Create your views here.

templates/about.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" type="image/png" href="../media/image/favicom.png" />
    <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    
    <link rel="stylesheet" href="{% static './css/about.css'%}" />
    <title>Quienes somos</title>
  </head>

  <body>
    <header>
      <h1><a href="/">BULLÉ</a></h1>
      <nav>
        <ul>
          <li><a href="/">HOME</a></li>
          <li><a href="{% url 'info' %}">+ INFO</a></li>
          <li><a href="{% url 'shop' %}">SHOP</a></li>
          <li><a href="{% url 'contacto' %}">CONTACTO</a></li>
        </ul>
      </nav>
    </header>

    <main>
      <div class="articulo">
        <h1>Acerca de nosotros <br /></h1>
        <article>
          <br />
          En Bullé, nuestra misión es clara: celebrar la diversidad y la
          autenticidad a través de nuestros diseños de bikinis.<br />
          Nos enorgullece empoderar a las mujeres, independientemente de su
          forma, tamaño o estilo individual. <br />
        </article>
      </div>

      <div class="glass-container">
        <h1>Local</h1>
        <p>Estamos ubicados en Monroe 2083, Belgrano CABA</p>
        <br />
        <iframe
          class="map-iframe"
          src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d3285.889028712315!2d-58.457001!3d-34.556365!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x95bcb42c79a2de3b%3A0x95697356411640b5!2sAv.%20Monroe%202083%2C%20C1428%20CABA!5e0!3m2!1ses-419!2sar!4v1697600972855!5m2!1ses-419!2sar"
          width="100%"
          height="450"
          style="border: 0"
          allowfullscreen=""
          loading="lazy"
          referrerpolicy="no-referrer-when-downgrade"
        ></iframe>
      </div>
    </main>

    <footer class="footer">
      <div class="caja-footer">
        <a href="https://www.instagram.com/bulle.arg">
          <i class="fa fa-instagram"></i>
          <span class="icon-text">Seguinos en Instagram</span>
        </a>
        <a href="https://www.facebook.com/Bulle.arg">
          <i class="fa fa-facebook"></i>
          <span class="icon-text">Seguinos en Facebook</span>
        </a>
        <a href="mailto:bulle.bikinis@gmail.com">
          <i class="fa fa-envelope"></i>
          <span class="icon-text">Envianos un mail</span>
        </a>
        <a href="./assets/pages/product.html">
          <i class="fa fa-map-marker"></i>
          <span class="icon-text">Belgrano CABA</span>
        </a>
      </div>
    </footer>
  </body>
</html>

templates/base_template.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    
    
    <link rel="icon" type="image/png" href="{% static '/media/image/favicom.png'%}." />


    {% block contenido %} {% endblock  %}

</html>    

templates/contact.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="../css/style.css" />
    <link rel="stylesheet" href="{% static './css/contact.css'%}" />
    <link rel="icon" type="image/png" href="../media/image/favicom.png" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>Contacto</title>
    
  </head>
  <body>
    <header>
      <h1><a href="/">BULLÉ</a></h1>
      <nav>
        <ul>
          <li><a href="/">HOME</a></li>
          <li><a href="{% url 'info' %}">+ INFO</a></li>
          <li><a href="{% url 'shop' %}">SHOP</a></li>
          <li><a href="{% url 'contacto' %}">CONTACTO</a></li>
        </ul>
      </nav>
    </header>
    
      <div id="mayorista">
				<br>
				<a href="{% url 'mayorista' %}">Ingresa para compras mayoristas</a>
			  </div>
    </main>
    <main class="content">
      <section class="contact">
        <div class="u-wrapper">
          <div class="contact-content">
            <div class="contendorForm">
              <form
                id="form"
                class="form"
                action="https://formspree.io/f/xbjvpkpa"
                method="POST"
              >
                <h3 class="tag"><span>Contactate con nosotros</span></h3>
                <label for="name">Nombre completo <span>*</span></label>
                <input
                  name="name"
                  required
                  type="text"
                  id="name"
                  placeholder="Nombre"
                />
                <label for="email">Correo electronico <span>*</span></label>
                <input
                  name="email"
                  type="text"
                  id="email"
                  required
                  placeholder="Email"
                />
                <label for="message">Mensaje</label>
                <textarea name="message" id="message" cols="30" rows="10">
En que podemos ayudarte? 









                        </textarea
                >
                <button type="submit" class="btn primary full">
                  Enviar mensaje
                </button>
              </form>
            <!--</div>
            <a href="mailto:walterdiaz78@gmail.com" id="trucazo">mail</a>
          </div>-->
        </div>
      </section>
    </main>
      
        
    <footer class="footer">
      <div class="caja-footer">
          <a href="https://www.instagram.com/bulle.arg">
              <i class="fa fa-instagram"></i> <span class="icon-text">Seguinos en Instagram</span>
          </a>
          <a href="https://www.facebook.com/Bulle.arg">
              <i class="fa fa-facebook"></i> <span class="icon-text">Seguinos en Facebook</span>
          </a>
          <a href="mailto:bulle.bikinis@gmail.com">
              <i class="fa fa-envelope"></i> <span class="icon-text">Envianos un mail</span>
          </a>
          <a href="./assets/pages/product.html">
              <i class="fa fa-map-marker"></i> <span class="icon-text">Belgrano CABA</span>
          </a>
      </div>
  </footer>



    <script>
      const $form = document.querySelector("form");
      $form.addEventListener("submit", handleSubmit);
      async function handleSubmit(event) {
        event.preventDefault();
        const form = new FormData(this);
        const response = await fetch(this.action, {
          method: this.method,
          body: form,
          headers: {
            accept: "aplication/json",
          },
        });
        if (response.ok) {
          this.reset;
          alert("Gracias por escribirnos, pronto nos pondremos en contacto");
        }
      }
    </script>
    
  </body>
</html>

templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    
    <link rel="stylesheet" href="{% static './css/style.css'%}" />
    <link rel="icon" type="image/png" href="{% static '/media/image/favicom.png'%}." />
    <title>Bulle</title>
  </head>

  <body>
    <header>
      <h1><a href="/">BULLÉ</a></h1>
      <nav>
        <ul>
          <li><a href="/">HOME</a></li>
          <li><a href="{% url 'info' %}">+ INFO</a></li>
          <li><a href="{% url 'shop' %}">SHOP</a></li>
          <li><a href="{% url 'contacto' %}">CONTACTO</a></li>
        </ul>
      </nav>
    </header>

    <main>
      <a href="https://bulle.mercadoshops.com.ar/" target="_blank">
        <h3 class="caption">Collection SS24</h3>
        <!-- boton sobre foto-->
      </a>

      <section class="container">
        <div class="content">
          <p>
            En BÚLLE sabemos que cada cuerpo es unico y soñamos con realizar un
            marca autentica, con diseños exclusivos, y moldes pensados para que
            se adapten a cada necesidad. Contamos con una curva de 5 talles y trabajamos
            para compensar el daño de las publicidades generando confianza, inclusion y belleza.
          </p>
        </div>
      </section>

      <a href="https://wa.me/541151186423"
        class="whatsapp"
        target="_blank"
      >
        <i class="fa fa-whatsapp whatsapp-icon"></i
      ></a>
    </main>

    <footer class="footer">
      <div class="caja-footer">
        <a href="https://www.instagram.com/bulle.arg">
          <i class="fa fa-instagram"></i>
          <span class="icon-text">Seguinos en Instagram</span>
        </a>
        <a href="https://www.facebook.com/Bulle.arg">
          <i class="fa fa-facebook"></i>
          <span class="icon-text">Seguinos en Facebook</span>
        </a>
        <a href="mailto:bulle.bikinis@gmail.com">
          <i class="fa fa-envelope"></i>
          <span class="icon-text">Envianos un mail</span>
        </a>
        <a href="./pages/product.html">
          <i class="fa fa-map-marker"></i>
          <span class="icon-text">Belgrano CABA</span>
        </a>
        <a href="tienda/">Admin</a>
      </div>
    </footer>
  </body>
</html>

templates/mayorista.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@500;700&display=swap" rel="stylesheet">  
	<link rel="stylesheet" href="{% static './css/mayorista.css'%}">
	<title>Bullé Mayorista</title>
</head>
<body>
	<div class="contenedor">
		<div class="columna-izquierda">
			<div class="registro activo" id="registro">
				<div class="header">
					<h1>Bullé - Venta mayorista</h1>
					<p>Dejanos tus datos y nos pondremos en contacto</p>
				</div>
		
				<form class="formulario" id="formulario">
					<label for="nombre">Nombre</label>
					<div class="contenedor-input">
						<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
							<path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
							<path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
						</svg>
						<input type="text" id="nombre" name="nombre" placeholder="Ingresa tu nombre y apellido">
					</div>
		
					<label for="correo">Correo Electrónico</label>
					<div class="contenedor-input">
						<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-envelope" viewBox="0 0 16 16">
							<path d="M0 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V4zm2-1a1 1 0 0 0-1 1v.217l7 4.2 7-4.2V4a1 1 0 0 0-1-1H2zm13 2.383-4.758 2.855L15 11.114v-5.73zm-.034 6.878L9.271 8.82 8 9.583 6.728 8.82l-5.694 3.44A1 1 0 0 0 2 13h12a1 1 0 0 0 .966-.739zM1 11.114l4.758-2.876L1 5.383v5.73z"/>
						</svg>
						<input type="text" id="correo" name="correo" placeholder="Ingresa tu correo electronico">
					</div>
					
					<label for="telefono">Teléfono</label>
					<div class="contenedor-input">
						<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-telephone" viewBox="0 0 16 16">
							<path d="M3.654 1.328a.678.678 0 0 0-1.015-.063L1.605 2.3c-.483.484-.661 1.169-.45 1.77a17.568 17.568 0 0 0 4.168 6.608 17.569 17.569 0 0 0 6.608 4.168c.601.211 1.286.033 1.77-.45l1.034-1.034a.678.678 0 0 0-.063-1.015l-2.307-1.794a.678.678 0 0 0-.58-.122l-2.19.547a1.745 1.745 0 0 1-1.657-.459L5.482 8.062a1.745 1.745 0 0 1-.46-1.657l.548-2.19a.678.678 0 0 0-.122-.58L3.654 1.328zM1.884.511a1.745 1.745 0 0 1 2.612.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.678.678 0 0 0 .178.643l2.457 2.457a.678.678 0 0 0 .644.178l2.189-.547a1.745 1.745 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.634 18.634 0 0 1-7.01-4.42 18.634 18.634 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877L1.885.511z"/>
						</svg>
						<input type="text" id="telefono" name="telefono" placeholder="Ingresa un telefono de contacto">
					</div>
		
					<div class="contenedor-boton">
						<button type="submit">
							Registrame
							<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-check" viewBox="0 0 16 16">
								<path d="M10.97 4.97a.75.75 0 0 1 1.07 1.05l-3.99 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.267.267 0 0 1 .02-.022z"/>
							</svg>
						</button>
					</div>
				</form>
			</div>
			<div id="volver">
				<br>
				<a href="{% url 'index' %}">Volver al inicio</a>
			  </div>

			<div class="header exito" id="exito">
				<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-check-circle" viewBox="0 0 16 16">
					<path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
					<path d="M10.97 4.97a.235.235 0 0 0-.02.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-1.071-1.05z"/>
				</svg>
				<h1>Registrado!</h1>
				<p>Te contactaremos a la brevedad.</p>
			</div>
		</div>

		<div class="columna-derecha">

		</div>
	</div>

	<script src="/assets/js/app.js"></script>
</body>
</html>

templates/product.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/png" href="../media/image/favicom.png">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Agrega estos enlaces en la sección head de tu HTML para cargar Slick Carousel -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.min.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static './css/product.css'%}">
    <title>Bulle</title>


</head>

<body>
    <header>
        <h1><a href="/">BULLÉ</a></h1>
        <nav>
            <ul>
              <li><a href="/">HOME</a></li>
              <li><a href="{% url 'info' %}">+ INFO</a></li>
              <li><a href="{% url 'shop' %}">SHOP</a></li>
              <li><a href="{% url 'contacto' %}">CONTACTO</a></li>
            </ul>
          </nav>
        
      </header>
      <main>
        <div class="bloc">
            <div class="owl-carousel">
                <div class="bloc_bis enterizas">
                    <a href="https://bulle.mercadoshops.com.ar/enterizas" target="_blank"><img src="{% static '/media/image/Polish_20221019_221519275.jpg'%}" alt="">Enterizas</a>
                </div>
        
                <div class="bloc_bis tops">
                    <a href="https://bulle.mercadoshops.com.ar/tops" target="_blank"><img src="{% static '/media/image/carreZoom6.jpg'%}" alt="">Tops</a>
                </div>
        
                <div class "bloc_bis bikini inferior">
                    <a href="https://bulle.mercadoshops.com.ar/bottom" target="_blank"><img src="{% static '/media/image/zooom.jpg'%}" alt="">Bottom</a>
                </div>
        
                <div class="bloc_bis entera">
                    <a href="https://bulle.mercadoshops.com.ar/enterizas" target="_blank"><img src="{% static '/media/image/Polish_20221019_221034993.jpg'%}" alt="">Enterizas</a>
                </div>
        
                <div class="bloc_bis unapieza">
                    <a href="https://bulle.mercadoshops.com.ar/tops" target="_blank"><img src="{% static '/media/image/SDFDDG.jpg'%}" alt="">Tops</a>
                </div>
        
                <div class="bloc_bis bikini dospiezas">
                    <a href="https://bulle.mercadoshops.com.ar/bottom" target="_blank"><img src="{% static '/media/image/botom2.jpg'%}" alt="">Bottoms</a>
                </div>
            </div>
        </div>
        
        
    
          
    </main>
    
    <footer class="footer">
      <div class="caja-footer">
          <a href="https://www.instagram.com/bulle.arg">
              <i class="fa fa-instagram"></i> <span class="icon-text">Seguinos en Instagram</span>
          </a>
          <a href="https://www.facebook.com/Bulle.arg">
              <i class="fa fa-facebook"></i> <span class="icon-text">Seguinos en Facebook</span>
          </a>
          <a href="mailto:bulle.bikinis@gmail.com">
              <i class="fa fa-envelope"></i> <span class="icon-text">Envianos un mail</span>
          </a>
          <a href="./assets/pages/product.html">
              <i class="fa fa-map-marker"></i> <span class="icon-text">Belgrano CABA</span>
          </a>
      </div>
  </footer>
      
</body>
    
<script>
    $(document).ready(function(){
      $('.owl-carousel').owlCarousel({
        items: 5, // Número de elementos a mostrar en el carrusel
        loop: true, // Repetir el carrusel
        autoplay: true, // Reproducción automática
        autoplayTimeout: 3000, // Intervalo de tiempo de la reproducción automática en milisegundos
        
        margin: 10, // Espacio entre elementos
        responsive:{
          0:{
            items: 1 // Número de elementos a mostrar en pantallas pequeñas
          },
          600:{
            items: 2 // Número de elementos a mostrar en pantallas medianas
          },
          1000:{
            items: 3 // Número de elementos a mostrar en pantallas grandes
          }
        }
      });
    });
  </script>
  
  
</html>

tienda_app/templates/tienda.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    
    <link rel="stylesheet" href="{% static './css/tienda.css'%}" />
    <link rel="icon" type="image/png" href="{% static '/media/image/favicom.png'%}." />
    <title>Tienda</title>
  </head>

  <body>
    <header>
      <h1><a href="/">BULLÉ</a></h1>
      <nav>
        <ul>
          <li><a href="/">HOME</a></li>
          <li><a href="{% url 'info' %}">+ INFO</a></li>
          <li><a href="{% url 'shop' %}">SHOP</a></li>
          <li><a href="{% url 'contacto' %}">CONTACTO</a></li>
        </ul>
      </nav>
    </header>

    <main>
        <div>
            <h2>Tiendas</h2>
            <h2><a href="{% url 'tienda:create' %}">Crear una tienda</a></h2>
            <div class="list">
                {% for tienda in tienda_list %}
                <fieldset class="tienda-box">
                    <legend>Nombre: {{tienda.nombre}}</legend>
                    <ul>
                        <li>Direccion de la tienda: {{tienda.ubicacion}}</li>
                        <li>Contacto: {{tienda.contacto}}</li>
                        <li>Rubro: {{tienda.rubro}}</li>
                        <li>Fecha de alta: {{tienda_fecha_habilitacion}}</li>
                    </ul>

                    <div>
                        
                        <a href="{% url 'tienda:detail' tienda.id %}">Detalle de {{tienda.nombre}} 🟢</a>
                    </div>
                    <div>
                        
                        <a href="{% url 'tienda:delete' tienda.id %}">Borrar {{tienda.nombre}} ❌</a>
                    </div>
                    <div>
                        <label for="">Editar</label>
                        <a href="{% url 'tienda:update' tienda.id %}">Editar {{tienda.nombre}} 📎</a>
                    </div>
                </fieldset>
                {% endfor %}
            </div>
        </div>
      
    </main>

    <footer>
      
    </footer>
  </body>
</html>